### PR TITLE
Added Router Functionality

### PR DESCRIPTION
**Pull request by yogeshtakeo**
#Router Functionality added to the application

The application is now invoked with the multi page feeling.

Screenshot 2024-03-08 at 2 19 36 PM

### CODE REVIEW

**Comment by gsajan21** [comment]
approved

**Comment by Aakash-codes-git** [comment]
approved

**Review by Aakash-codes-git — COMMENTED** [review]
approved

**Review by sonamLama22 — COMMENTED** [review]
.

**Pull request merged**
